# Learning Numpy Lib

In [1]:
import numpy as np

In [2]:
list = [1,2,3,65,145]

In [3]:
myarr = np.array([list], np.int64)

In [4]:
myarr

array([[  1,   2,   3,  65, 145]], dtype=int64)

In [5]:
myarr[0]

array([  1,   2,   3,  65, 145], dtype=int64)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr.shape

(1, 5)

In [8]:
myarr[0,1] = 85

In [9]:
myarr

array([[  1,  85,   3,  65, 145]], dtype=int64)

# Numpy array creation

In [10]:
newarr = np.array([[1,2,3,4,6],[7,4,1,2,5],[9,6,2,3,4]])

In [11]:
newarr

array([[1, 2, 3, 4, 6],
       [7, 4, 1, 2, 5],
       [9, 6, 2, 3, 4]])

In [12]:
newarr.dtype

dtype('int32')

In [13]:
newarr.shape

(3, 5)

In [14]:
newarr.size

15

In [15]:
np.array({34,5,1,6})

array({1, 34, 5, 6}, dtype=object)

In [16]:
zero = np.zeros((2,5))

In [17]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zero.dtype

dtype('float64')

In [19]:
zero.size

10

In [20]:
zero.shape

(2, 5)

# Range function

In [21]:
# creates a numpy array upto 15
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace= np.linspace(1,5,4)

In [24]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [25]:
emp  = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.95819673e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.33511290e-306, 1.78019082e-306, 8.45559303e-307],
       [8.06613040e-308, 6.89810244e-307, 1.22387550e-307,
        2.22522596e-306, 8.34423917e-308, 9.79107193e-307]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [28]:
emp_like[0] = 45

In [29]:
emp_like

array([45.        ,  2.33333333,  3.66666667,  5.        ])

In [30]:
# to create a identity matrix
ide = np.identity(10)

In [31]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
ide.shape

(10, 10)

In [33]:
arng = np.arange(45)

In [34]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [35]:
# customing the martix shape
arng.reshape(5,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [36]:
# to create 1-D array
arng.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [37]:
arng.shape

(45,)

# Axis

In [38]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [41]:
# row wise sum
ar.sum(axis = 0)

array([12,  8,  9])

In [42]:
# column wise sum
ar.sum(axis =1)

array([ 6, 15,  8])

In [43]:
# Transpose means rows to columns and columns to rows
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [46]:
# to find the number of dimensions
ar.ndim

2

In [47]:
# Number of elements
ar.size

9

In [48]:
ar.nbytes

36

# 1-D Array

In [49]:
one = np.array([1,2,3,45,6,8])

In [50]:
# gives index at which max value is present
one.argmax()

3

In [51]:
# gives indexs array which tells that if the values are in this indexes than it get sorted
one.argsort()

array([0, 1, 2, 4, 5, 3], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
# tells that at 8th index had minimum value
ar.argmin()

8

In [54]:
ar.argmax(axis = 0)  # see matrix as columns  0 1 2

array([2, 1, 1], dtype=int64)

In [55]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [56]:
ar.argsort(axis =0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [57]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [58]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

# operation on matrix

In [59]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [60]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [61]:
# adding two matrix

ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [62]:
# multipling two matrix
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [63]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [64]:
ar.sum()

29

In [65]:
ar.max()

7

In [66]:
ar.min()

0

# finding elements from matrix

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
np.where(ar >= 4)

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [69]:
np.count_nonzero(ar)   # number of non-zero elements

8

In [70]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [71]:
import sys

In [72]:
py_ar  = [0,4,55,2]

In [73]:
np_arr = np.array(py_ar)

In [74]:
sys.getsizeof(1) * len(py_ar)

112

In [75]:
np_arr.itemsize * np_arr.size   # numpy array is better and fast then normal list

16